---
- name: Create Nginx application
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('file', 'base.yaml')}}"

- name: Wait 2 minutes for nginx deployment
  k8s_facts:
    api_version: "apps/v1"
    kind: "Deployment"
    namespace: "nginx-example"
    label_selectors:
      - "app = nginx"
  register: deploy
  until: deploy and deploy.resources[0].status.replicas == deploy.resources[0].status.get("availableReplicas", 0)
  retries: 10
  delay: 10

- name: Create ark backup of nginx
  k8s:
    state : "{{ state }}"
    definition: "{{ lookup('file', 'create-backup.yml')}}"

- name: Wait 1 minute for backup to complete
  k8s_facts:
    api_version: "ark.heptio.com/v1"
    kind: "Backup"
    namespace: "heptio-ark"
  register: backup
  until: backup and backup.resources[0].status.get("phase", 0) == "Completed"
  retries: 10
  delay: 5
