---
- name: Delete nginx namespace to simulate DR
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: nginx-example
        labels:
          app: nginx

- name: Wait 2 minutes for namespace to be deleted
  k8s_facts:
    api_version: "v1"
    kind: "Namespace"
    namespace: "nginx-example"
    name: "nginx-example"
  register: ns
  until: not ns
  retries: 10
  delay: 5


- name: Create ark restore of nginx
  k8s:
    state: present
    definition: "{{ lookup('file', 'create-restore.yml')}}"

- name: Wait 3 minutes for restore to finish
  k8s_facts:
    api_version: "apps/v1"
    kind: "Restore"
    namespace: "heptio-ark"
    name: "nginx-backup"
  register: restore
  until: restore and restore[0].status.get("phase", 0) == "Completed"
  retries: 20
  delay: 10

- name: Wait 2 minutes for nginx deployment
  k8s_facts:
    api_version: "apps/v1"
    kind: "Deployment"
    namespace: "nginx-example"
    label_selectors:
      - "app = nginx"
  register: deploy
  until: deploy and deploy.resources[0].status.replicas == deploy.resources[0].status.get("availableReplicas", 0)
  retries: 10
  delay: 10

- name: Delete ark restore of nginx (workaround to use common name for restore)
  k8s:
    state: absent
    definition: "{{ lookup('file', 'create-restore.yml')}}"

